# Generated by Django 5.2.3 on 2025-08-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_views_earnings_to_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='cpm_rate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cpm_rate',
        ),
    ]
