# Generated by Django 5.2.3 on 2025-08-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_campaign_cpm_rate_remove_userprofile_cpm_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('features', models.TextField(help_text='List of features included in the plan')),
                ('is_popular', models.BooleanField(default=False, help_text='Is this plan popular?')),
            ],
        ),
    ]
