# Generated by Django 5.2.3 on 2025-08-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default=1, help_text='Description of the plan'),
            preserve_default=False,
        ),
    ]
